<div id="invitesplash">

<h1>Invite Your Friends and Share $40!</h1>

<div class="cf">

<div id="invite-you">

<h2>You get<br>
<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/volo_giftfinal2.jpg" alt="$20 gift card" /><br>
$20 every time a friend makes<br>
their first purchase*
</h2>

<ul class="prizes cf">
<li>
<a href="<?php echo Mage::getBaseUrl(); ?>lighting/j-black.html"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/prize-jalen.jpg" alt="Jalen Light" /></a><br>
<strong>4 friends</strong><br>
gets you a<br>
<a href="<?php echo Mage::getBaseUrl(); ?>lighting/j-black.html">Jalen Light</a>
</li>
<li>
<a href="<?php echo Mage::getBaseUrl(); ?>chairs/harris-adjustable-barstool-natural-ash-and-steel.html"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/prize-harris.jpg" alt="Harris Stool" /></a><br>
<strong>8 friends</strong><br>
gets you a<br>
<a href="<?php echo Mage::getBaseUrl(); ?>chairs/harris-adjustable-barstool-natural-ash-and-steel.html">Harris Stool</a>
</li>
<li>
<a href="<?php echo Mage::getBaseUrl(); ?>sofas/armchairs/cameron-ottoman-oatmeal-linen.html"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/prize-cameron.jpg" alt="Cameron Armchair" /></a><br>
<strong>25 friends</strong><br>
gets you a<br>
<a href="<?php echo Mage::getBaseUrl(); ?>sofas/armchairs/cameron-ottoman-oatmeal-linen.html">Cameron Armchair</a>
</li>
</ul>

</div>

<div id="invite-friend">

<h2>Your friend gets<br>
<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/volo_giftfinal.jpg" alt="$20 gift card" /><br>
$20 off their first purchase
</h2>

<button class="button" title="Invite friends" type="button"><a href="<?php echo Mage::getBaseUrl(); ?>invitefriend">Invite friends now &raquo;</a></button>

<p class="note">* Your friend must spend a minumum of $75</p>

</div>

</div>

</div>
