<?php
/**
 * Magebase
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magebase. (http://magebase.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php 
$_comment = $this->getLayout()->createBlock('checkoutcomment/widget_comment');
if ($_comment->isEnabled()) : ?>
    <div class="field">
        <?php echo $_comment->setComment($this->getQuote()->getCustomerNotes())->setFieldIdFormat('%s')->setFieldNameFormat('%s')->toHtml() ?>
    </div>
<?php endif; ?>