<?php $_invitecode=$this->getInviteCode() ?>
<STYLE TYPE="text/css" MEDIA=screen>
.share { background: #F8F8F8; border:1px solid #CCC; padding: 8px; margin:0 0 5px 0;}
.email-friend a {display:block; margin:0 10px 0 0; float:left;clear:both;width:55px;height:20px;background:url(../images/email.png) no-repeat; font-size:0;text-decoration:none; text-indent:-9999px; }
.tweet { float: left; width: 55px; height:20px; margin-right: 10px;}
.fbShare { float: left; width: 175px; height: 20px;}
</STYLE>

<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<h2>Invite Friends And Share $40</h2>
<div>
	<p>Get $20 off each friend you refer who makes their first purchase.</p>
	<p>Your friend also gets $15 off with the discount code you give them. Everyone wins!</p>
</div>
<div>
	<form id="email_invite_form">	
	<input type="hidden" id="email_counter" name="email_counter" value="0">
		<h3>Email invitations to Friends</h3>
		<div id="emaillist">
			<input type="text" id="invite_email_0" name="invite_email_0" class="invite_email" placeholder="Email">
		</div>
		<div id="addemail">+Add person to invite</div>
		<div class="message">
			<h4>Message</h4>
			<Textarea id="invite_message" name="invite_message">
			Hi, check out Volodesign.com - my new favourite site. They create beautifully designed furniture and leisure accessories, with prices up to 70% off high street. Best of all, enter <?php echo $_invitecode;?> at checkout for $15 off your first order!
			</Textarea>
		</div>
		<input type="button" id="submit_invite" name="submit" value="SEND INVITES">
	</form>
	<p> - OR -</p>
	<p>Share your invite link</p>
	<input type="text" id="share" name="share" value="<?php echo $_invitecode;?>">
<div class="share">    
	<div class="tweet"><a href="http://twitter.com/share" class="twitter-share-button" data-url="http://staging.studiovolo.com" data-count="none" data-via="Prices up to 70% off high street. Best of all, enter <?php echo $_invitecode;?> at checkout for $15 off your first order!">Share invites on Twitter</a></div>
     <div class="fbShare"><script src="http://platform.twitter.com/widgets.js" type="text/javascript" ></script><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=258344844295146&amp;xfbml=1"></script><fb:send href="http://staging.studiovolo.com" send="true" layout="button_count" width="250" show_faces="false" font=""></fb:send></div>    
     <br style="clear:both;" />
</div>

</div>
<script type="text/javascript">
//<![CDATA[
	var counter=0;
	$j('#addemail').bind('click', function(){
		counter++;
		$j("#emaillist").append('<input type="text" id="invite_email_'+counter+'" name="invite_email_'+counter+'" class="invite_email" placeholder="Email">');
		$j("#email_counter").attr('value',counter);
	});

	$j('#submit_invite').bind('click', function(){
		var data = jQuery('#email_invite_form').serialize();
		data += '&isAjax=1';
		alert(data);
		$j.ajax({
			url: '/invitefriend/index/sendinvite',
			dataType: 'json',
			type : 'post',		
			data : data,
			success: function(data){
				alert(data.result);
			},
			error: function(data){
				alert("error");
			}
		});
	});

//]]>
</script>
