<?php
/**
 * Magebase
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magebase. (http://magebase.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<label for="<?php echo $this->getFieldId('customer_notes')?>"><?php echo $this->__('Special delivery instructions') ?> <span id="charsleft"></span></label>
<div class="input-box">
    <textarea maxlength="100" id="<?php echo $this->getFieldId('customer_notes')?>" name="<?php echo $this->getFieldName('customer_notes')?>" class="input-text" <?php echo $this->getFieldParams() ?> placeholder="Buzzer code, place to leave package..."><?php echo $this->htmlEscape($this->getComment()) ?></textarea>
</div>
<script type="text/javascript">
$j('#<?php echo $this->getFieldId('customer_notes')?>').keyup(function () {
    var left = 100 - $j(this).val().length;
    if (left < 0) {
        left = 0;
    }
    if(left < 100) {
        $j('#charsleft').text('(' + left + ' characters left)');
    } else {
        $j('#charsleft').text('');        
    }
});
</script>
