<div id="login-wrap">

	<h3>Already a Customer?</h3>

	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="errormsg"></div>
	<form action="#" method="post" id="login-form" class="frm-login">
		<p>
			<label for="email">Email</label>
			<input name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" type="text" class="input-text required-entry" title="<?php echo $this->__('Email Address') ?>" />
		</p>
		<p>
			<label for="pass">Password</label>
			<input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
		</p>
		<p>
			<button class="action-btn" type="submit" name="send" id="send2"><?php echo $this->__('Login') ?></button>
		</p>
		<p class="forgot">
			<a href="#" onclick="$j('#login-wrap').stop(true,true).slideUp(); $j('#fpass').stop(true,true).slideDown(); return false;">forgot password?</a>
		</p>
	</form>
<!--	
	<div style="display:none;" id="fpass" class="cf">
		<form class="for-pass" id="forgot-form" method="post" action="<?php echo $this->getUrl('customer/account/ajaxForgotPassword/') ?>">
			<p style="padding-left: 30px;"><?php echo $this->__('Please enter your email to get the password') ?></p>
			<p>
				<label class="required" for="email"><?php echo $this->__('Email') ?></label>
				<input type="text" title="Email Address" class="input-text required-entry validate-email" id="forgot_email" value="" name="forgotemail">
			</p>		
			<p>
				<button type="button" id="send3" name="send3" class="action-btn" onclick="return forgetpass();"><span><?php echo $this->__('Submit') ?></span></button>
			</p>
			<p class="forgot">
				<a href="#" onclick="$j('#login-form').stop(true,true).slideDown(); $j('#fpass').stop(true,true).slideUp(); return false;">return to login</a>
			</p>
		</form>
	</div>
-->		
	<div class="signup cf">
		<h4>Don't have an account?</h4>
		<button type="button">Sign Up</button>
	</div>

</div>



<div id="signup-wrap" style="display: none;">

	<h3>Create an Account</h3>
	<form action="#" method="post" id="regis-form" class="frm-regis">
		<div class="errormsg validation-advice-top"></div>
<!-- Removed on 11/12/2012 https://basecamp.com/1772300/projects/1246319-volo/todos/22599451-checkout-signup
                <p>
                        <label for="firstname">First Name</label>
                        <input id="firstname" class="input-text" type="text" title="First Name" value="" name="firstname" />
                </p>
                <p>
                        <label for="lastname">Last Name</label>
                        <input id="lastname" class="input-text" type="text" title="Last Name" value="" name="lastname" />
                </p>
-->
		<p>
			<label for="email_address">Email</label>
			<input id="email_address" class="input-text validate-email required-entry" type="text" title="Email Address" value="" name="email" />
		</p>
		<p>
			<label for="password">Password</label>
			<input id="password" class="input-text required-entry validate-password" type="password" title="Password" name="password"/>
		</p>
		<p>
			<label for="confirmation">Confirm Password</label>
			<input id="confirmation" class="input-text required-entry validate-password" type="password" title="Password" name="confirmation"/>
		</p>
		<p style="padding: 10px 0 5px;">
			<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" checked="checked"/>
			<label style="width: auto; display: inline;" for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
		</p>
		<p class="terms">
			By clicking Sign Up, you agree to our <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>.
		</p>		
		<p>
			<button type="submit" class="action-btn">Sign Up</button>
		</p>
		<p class="existing">
                        <a href="#" onclick="$j('#signup-wrap').stop(true,true).slideUp(); $j('#login-wrap').stop(true,true).slideDown(); $j('#alogin').colorbox.resize({
                                                        innerWidth: 390,
                                                        innerHeight: 278,
                                                }); return false;">Already have an account?</a>
                </p>
	</form>
<!--
	<div style="display:none;" id="fpass2" class="cf">
                <form class="for-pass" id="forgot-form" method="post" action="<?php echo $this->getUrl('customer/account/ajaxForgotPassword/') ?>">
                        <p style="padding-left: 30px;"><?php echo $this->__('Please enter your email to get the password') ?></p>
                        <p>
                                <label class="required" for="email"><?php echo $this->__('Email') ?></label>
                                <input type="text" title="Email Address" class="input-text required-entry validate-email" id="forgot_email" value="" name="forgotemail">
                        </p>
                        <p>
                                <button type="button" id="send3" name="send3" class="action-btn" onclick="return forgetpass();"><span><?php echo $this->__('Submit') ?></span></button>
                        </p>
                        <p class="forgot">
                                <a href="#" onclick="$j('#regis-form').stop(true,true).slideDown(); $j('#fpass2').stop(true,true).slideUp(); return false;">return to sign up</a>
                        </p>
                </form>
        </div>

-->
</div>

<div style="display:none;" id="fpass" class="cf">
	<h3>Forgot Password</h3>
                <form class="for-pass" id="forgot-form" method="post" action="<?php echo $this->getUrl('customer/account/ajaxForgotPassword/') ?>">
			<p class="error" style="display:none; padding-left:30px; margin:0 0 15px 0; font-size:12px;"></p>
			<p class="control" style="display:none; padding-left:40px; font-size:12px; text-align:center;">This Pop-up will be closed in 5 seconds</p>
                        <p style="padding-left: 30px; margin:0 0 15px 0; font-size:13px;"><?php echo $this->__('Please enter your email to get the password') ?></p>
                        <p>
                                <label class="required" for="email"><?php echo $this->__('Email') ?></label>
                                <input type="text" title="Email Address" class="input-text required-entry validate-email" id="forgot_email" value="" name="forgotemail">
                        </p>
                        <p>
                                <button type="submit" class="action-btn"><?php echo $this->__('Submit') ?></button>
                </form>

	<p class="forgot">
		<a href="#" onclick="$j('#login-wrap').stop(true,true).slideDown(); $j('#fpass').stop(true,true).slideUp(); return false;">return to login</a>
        </p>

</div>

<script type="text/javascript">
	//<![CDATA[	
	$j('#login-form').unbind('submit').submit(function(e) {
		loginAjax();	
		e.preventDefault();
	});		
	
	$j('#regis-form').unbind('submit').submit(function(e) {
		registerAjax();
		e.preventDefault();
	});	


	$j('#forgot-form').unbind('submit').submit(function(e) {
                forgetpass();
                e.preventDefault();
        });

	
	//]]>
</script>





<?php /*

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('quicklogin/quicklogin.css');?>" media="all" />
<div id="quicklogin">
  <div class="quickbg" >
  
    <div class="page-title">
	    <h2><?php echo $this->__('Login or Create an Account') ?></h2>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	
	    <fieldset class="col2-set login-page">
		<legend><?php echo $this->__('Login or Create an Account') ?></legend>
		
		<div class="col-2 registered-users">
		   <form action="#" method="post" id="login-form" class="frm-login">
		    <div class="content">
			<h3><?php echo $this->__('Registered Customers') ?></h3>
			<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
			<ul class="form-list">
			    <li>
				<label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
				<input name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" type="text" class="input-text required-entry" title="<?php echo $this->__('Email Address') ?>" />
			    </li>
			    <li>
				<label for="pass"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
				<input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
			    </li>
			</ul>
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
		    </div>
		    <div class="buttons-set">
			<div class="fpasscheck">
			  <input type="checkbox" name="modtype" value="value1" onclick="showForgotSection('fpass', this)" />
			  <span><?php echo $this->__('Forgot Your Password?') ?></span>
			</div>
			<button class="action-btn" type="button" name="send" id="send2" onclick="loginAjax();"><?php echo $this->__('Login') ?></button>
			
		    </div>
		    </form>
			<div style="display:none;position: absolute;bottom:40px;" id="fpass">
					<form class="for-pass" id="forgot-form" method="post" action="<?php echo $this->getUrl('customer/account/ajaxForgotPassword/') ?>">
                    <p><?php echo $this->__('Please enter your email to get the password') ?></p>
                    <ul class="form-list">
                        <li>
                            <label class="required" for="email"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" title="Email Address" class="input-text required-entry validate-email" id="forgot_email" value="" name="forgotemail">
                            </div>
                        </li>
                      
                    </ul>
					<div style="border:0px;" class="col-2 registered-users">
						<div class="buttons-set">
			
				<button type="button" id="send3" name="send3" class="action-btn" onclick="return forgetpass();"><span><?php echo $this->__('Submit') ?></span></button>
							 <p style="display:none;" id="loading"></p> 
						</div>
                     </div>
                   
					</form>
					</div>
		</div>
		<div class="col-1 new-users">
		 <form action="#" method="post" id="regis-form" class="frm-regis">
		    <div class="content">
			<h3><?php echo $this->__('New Customers') ?></h3>
			
		        <div class="content">
				<ul class="form-list">
				    <li>
					<label for="email"><?php echo $this->__('First Name') ?> <span class="required">*</span></label><br />
					<input id="firstname" class="input-text required-entry" type="text" title="First Name" value="" name="firstname" />
				    </li>
				    
				     <li>
					<label for="pass"><?php echo $this->__('Last Name') ?> <span class="required">*</span></label><br />
					<input id="lastname" class="input-text required-entry" type="text" title="Last Name" value="" name="lastname" />
				    </li>
				     <li>
					<label for="pass"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
					<input id="email_address" class="input-text validate-email required-entry" type="text" title="Email Address" value="" name="email" />
				    </li>

				     <li>
					<label for="pass"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
					<input id="password" class="input-text required-entry validate-password" type="password" title="Password" name="password"/>
				    </li>

				     <li>
					<label for="pass"><?php echo $this->__('Confirm Password') ?> <span class="required">*</span></label><br />
					<input id="confirmation" class="input-text required-entry validate-password" type="password" title="Password" name="confirmation"/>
				    </li>
                      <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
				</ul>
				<p class="required"><?php echo $this->__('* Required Fields') ?></p>
		        </div>			
					
		    </div>
		    <div class="buttons-set">
			<button type="button" class="action-btn" onclick="return registerAjax();"><span><?php echo $this->__('Create an Account') ?></span></button>
		    </div>
		    </form>
		</div>
	    </fieldset>
	
	<script type="text/javascript">
	//<![CDATA[
	     // var dataForm = new VarienForm('login-form', true);
	      //var dataForm1 = new VarienForm('regis-form', true);
	//]]>
	</script>
	</div>
	
</div>


*/ ?>
